services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres-momos
    platform: linux/x86_64
    environment:
      POSTGRES_DB: momos
      POSTGRES_USER: postgres # Replace with your database user
      POSTGRES_PASSWORD: postgres # Replace with your database password
    ports:
      - "5435:5432"
    networks:
      - momos-infra
    # volumes:
    #   - ./docker/postgresql:/docker-entrypoint-initdb.d
    #   - momos-pg-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: minio-momos
    platform: linux/x86_64  # Added for consistency
    ports:
      - "9005:9000"  # API port
      - "9001:9001"  # Console port
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    # volumes:
    #   -  momos-minio-data:/data
    networks:
      - momos-infra
    command: "server /data --console-address :9001"
    healthcheck: # Added health check
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3


networks:
  momos-infra:
    driver: bridge
    name: momos-infra

volumes:
  momos-pg-data:
  momos-minio-data:
