"""Backpopulate number_events for users

Revision ID: 655d9213c227
Revises: f6db50dd579a
Create Date: 2025-07-19 15:19:04.528419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm.session import Session

from scripts.sync import sync_user_relation_count

# revision identifiers, used by Alembic.
revision: str = '655d9213c227'
down_revision: Union[str, None] = 'f6db50dd579a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sync_user_relation_count(session=Session(op.get_bind()))
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
